clone_folder: c:\choco-packages
branches:
  only:
  - master
environment:
  matrix:
  - package: eclipse
  - local_deps: eclipse
    package: eclipse-eclemma
  - package: graphviz
  - package: megacmd
  - package: sqlworkbench
  - package: strings
install:
- ps: if ($env:local_deps) { $env:local_deps  -Split ";" | Foreach { choco pack "c:\choco-packages\$_\$_.nuspec" --outputdirectory $pwd } }
build_script:
- ps: choco pack "c:\choco-packages\$env:package\$env:package.nuspec" --outputdirectory $pwd
- ps: if ($env:APPVEYOR_PULL_REQUEST_TITLE -eq $null -or $env:APPVEYOR_PULL_REQUEST_TITLE -eq $env:package) { choco install -source "'.;chocolatey'" $env:package  }
- ps: if ($env:APPVEYOR_PULL_REQUEST_TITLE -eq $null -or $env:APPVEYOR_PULL_REQUEST_TITLE -eq $env:package) { choco uninstall $env:package  }
