clone_folder: c:\choco-packages
branches:
  only:
  - master
environment:
  matrix:
  - package: eclipse
  - local_deps: eclipse
    package: eclipse-eclemma
  - package: graphviz
  - package: megasync
  - package: strings
install:
- ps: if ($env:local_deps) { $env:local_deps  -Split ";" | Foreach { choco pack "c:\choco-packages\$_\$_.nuspec" --outputdirectory $pwd } }
build_script:
- ps: choco pack "c:\choco-packages\$env:package\$env:package.nuspec" --outputdirectory $pwd
- ps: choco install -source "'.;chocolatey'" $env:package
- ps: choco uninstall $env:package
